### ISSUE TITLE
Allow passing custom progressive-image background color

### ISSUE THREAD

**Issue by frankhn** [byliuyang/react-progressive-image#3]
Hi, Firstly thanks for making this tool. It really saved a lot. Kudos...
Anyway, I feel like we should have a way to pass that background colour, as it differs from site to site.

Can we contribute to this tool?

**Comment by naturetime10** [comment]
@frankhn Surely! You are welcome! Please email me at byliuyang11@gmail.com so that we can connect on Facebook!

**Comment by frankhn** [comment]
it would much better if we had something like this
with some animations showing the user that something is going on. I've seen it take a while for the blur show up.


![image](https://user-images.githubusercontent.com/33962360/75628223-9262bb00-5bdf-11ea-9d25-3c8462a64b74.png)

![image](https://user-images.githubusercontent.com/33962360/75628211-6d6e4800-5bdf-11ea-9fb6-8e553b508f57.png)

**Comment by naturetime10** [comment]
@frankhn Interesting... Could you please record a video? Is it because the thumbnail is too big or the Internet is too slow? I wonder what's going on here.

**Comment by frankhn** [comment]
My fault, I think it might be the reason, the thumbnail is too big. Anyway, what are the specs for generating these thumbnails?

**Comment by naturetime10** [comment]
@frankhn I remember the resolution I had for the thumbnail is pretty low. I am planning to create a website to produce thumbnail, host images, and generate code directly. In the future, as people suggested on Facebook, will also create webpack plugin to generate thumbnails dynamically.

**Comment by frankhn** [comment]
OK, sounds great @byliuyang , let me know if you need any contribution support.
